actor_activation: relu
actor_hidden_layers:
- 400
- 300
actor_lr: 0.0003
batch_size: 100
critic_activation: relu
critic_hidden_layers:
- 400
- 300
critic_lr: 0.0003
env_name: Pendulum-v1
exploration_noise: 0.1
gamma: 0.99
noise_clip: 1.0
policy_delay: 2
policy_noise: 0.2
replay_buffer_size: 1000000
seed: 42
start_timesteps: 1000
tau: 0.005
total_steps: 50000
