actor_activation: relu
actor_hidden_layers:
- 400
- 300
actor_lr: 0.001
batch_size: 1000
critic_activation: relu
critic_hidden_layers:
- 400
- 300
critic_lr: 0.001
env_name: MountainCarContinuous-v0
exploration_noise: 0.5
gamma: 0.99
noise_clip: 0.5
noise_type: normal
policy_delay: 2
policy_noise: 0.3
replay_buffer_size: 1000000
seed: 42
start_timesteps: 25000
tau: 0.005
total_steps: 50000
